<#
.SYNOPSIS
    This PowerShell script ensures that The password manager function in the Edge browser is disabled.

.NOTES
    Author          : Vaughn Veal
    LinkedIn        : https://www.linkedin.com/in/vlryn-veal-050420306/
    GitHub          : github.com/vveal1
    Date Created    : 2025-10-5
    Last Modified   : 2025-10-5
    Version         : 1.0
    CVEs            : N/A
    Plugin IDs      : N/A
    STIG-ID         : WN10-CC-000245

.TESTED ON
    Date(s) Tested  : 
    Tested By       : Vaughn Veal
    Systems Tested  : 
    PowerShell Ver. : 

.USAGE
    Example syntax:
#>

 registry path and value information
Powershell Script
